import type { Metadata } from 'next';
import { Aside } from '@/components/dashboard/aside';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-white text-gray-900 flex font-sans">
          <Aside />
          {children}
        </div>
      </body>
    </html>
  );
}
